#compiles all files in current dir into a single output file

override AUX_DIR?=_aux/
override AUX_EXT?=.o
override CC?=g++
override CFLGS?=-O3 #-p -pg
override IN_EXT?=.cpp
override IN_DIR?=./
override INCLUDE_DIRS?=-I/usr/include/GL
override LIBS?=-lglut -lGLU -lGL
override PREDEF?=#-DDEBUG -DPROFLING -DWINDOWS 				#preprocessor defines
override RUN_ARGS?=#0 1																#passed as command line args to bin on run
override OUT_DIR?=_out/
override OUT_EXT?=

INS:=$(wildcard $(IN_DIR)*$(IN_EXT))
INS_NODIR:=$(notdir $(INS))
AUXS_NODIR:=$(patsubst %$(IN_EXT),%$(AUX_EXT),$(INS_NODIR))
AUXS:=$(addprefix $(AUX_DIR),$(AUXS_NODIR))
OUT:=$(OUT_DIR)cheat$(OUT_EXT)

.PHONY: all clean mkdir run 

all: mkdir $(OUT)

run: all
	./$(OUT) $(RUN_ARGS)

$(OUT): $(AUXS)
	$(CC) $^ -o "$@" $(LIBS)

$(AUX_DIR)%$(AUX_EXT): $(IN_DIR)%$(IN_EXT)
	$(CC) $(PREDEF) $(INCLUDE_DIRS) $(CFLAGS) -c "$<" -o "$@"

mkdir:
	mkdir -p "$(AUX_DIR)"
	mkdir -p "$(OUT_DIR)"

clean:
	rm -rf $(AUX_DIR) $(OUT_DIR)
