#!/usr/bin/env bash
top="$(pwd)"
for t in \
    c \
    cpp \
    gcc \
    glibc \
    posix \
  ; do
  if ! make -C "$t" test; then
    echo "TEST FAILED: $t"
    exit 1
  fi
done
for t in \
    scons \
  ; do
  cd "${top}/${t}"
  if ! ./test; then
    echo "TEST FAILED: $t"
    exit 1
  fi
done
echo "ALL TESTS PASSED"
exit 0
