//sources:
    //<http://www.alexonlinux.com/signal-handling-in-linux>
    //<http://www.kernel.org/doc/man-pages/online/pages/man7/signal.7.html>

//signal handling (ex: INT as in linux ctrl+c)
//6 signals defined:
    //SIGABRT (Signal Abort) Abnormal termination, such as is initiated by the abort function.
    //SIGFPE  (Signal Floating-Point Exception) Erroneous arithmetic operation, such as zero divide or an operation resulting in overflow (not necessarily with a floating-point operation).
    //SIGILL  (Signal Illegal Instruction) Invalid function image, such as an illegal instruction. This is generally due to a corruption in the code or to an attempt to execute data.
    //SIGINT  Generally generated by the user. Sample cause: bash ctrl+c.
    //SIGSEGV (Signal Segmentation Violation) Invalid access to storage: When a program tries to read or write outside the memory it has allocated.
    //SIGTERM (Signal Terminate) Termination request sent to program. Major cause: shutdown, window close.
//functions defined (handlers)
    //SIG_DFL Default handling: The signal is handled by the default action for that particular signal.
    //SIG_IGN Ignore Signal: The signal is ignored.
    //SIG_ERR Special return value indicating failure.

#include <stdio.h>
#include <signal.h>

#ifdef POSIX
#include <unistd.h>
//more signals in unistd
    //SIGKILL
    //SIGSTOP
        //programs cannot handle those signals
        //sigkill kills immeiatelly
        //sigstop stops immediatelly. ctrl+z.
    //SIGHUP
        //someone killed controlling terminal
    //SIGPIPE
        //write to pipe with no readers on other side
    //SIGCHLD
        //child terminated
    //SIGTSTP
    //SIGTTIN
    //SIGTTOU
    //SIGALRM
        //received after the alarm call after given no of secs
    //SIGUSR1 and SIGUSR2: left to users
#endif

void signal_handler(int sig)
{
    //sig arg allows us to use a single function for several different signals
    printf("sig: %d\n", sig);
    (void) signal(SIGINT, SIG_DFL);
      //reassign SIGINT to SIG_DFL handler which takes the default action for the signal
      //each process has a default action
      //in linux, the default actions are:
        //Term   Default action is to terminate the process.
        //Ign    Default action is to ignore the signal.
        //Core   Default action is to terminate the process and dump core (see core(5)).
        //Stop   Default action is to stop the process.
        //Cont   Default action is to continue the process if it is currently stopped.
      //the most common being Term
}


int main()
{
    (void) signal(SIGINT, signal_handler);
    (void) signal(SIGTERM, signal_handler);
        //registers signal_handler as handler for SIGINT and SIGTERM

    while(1)
    {
        puts("a");
#ifdef POSIX
        sleep(1);
#endif
    }
}
