#!/usr/bin/env bash
set -eu
top="$(pwd)"
log_path="${top}/test.log"
./clean
for d in */; do
  cd "${top}/${d}"
  if [ -e test ]; then
    echo "$d"
    ret=0
    ./test >> "$log_path" 2>&1 || ret=$?
    if [ $? -ne 0 ]; then
      echo "Test failed: ${d}"
    fi
  fi
done
echo 'All tests passed'
